name: PaddleDy2staicTests

on:
  push:
    branches: [develop]
  pull_request:
  workflow_dispatch:

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8']
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: ./tests/
        run: |
          wget  https://paddle-ci.gz.bcebos.com/dy2st/fallback/paddlepaddle-0.0.0-cp38-cp38-linux_x86_64.whl
          pip install paddlepaddle-0.0.0-cp38-cp38-linux_x86_64.whl
          git clone https://github.com/PaddlePaddle/Paddle
          cd Paddle
          git remote add upstream https://github.com/PaddlePaddle/Paddle
          git fetch upstream pull/54202/head:symbolic_translate
          git checkout symbolic_translate
          rm -f ./test/test_write_python_container.py
          rm -f ./test/test_slice.py
          rm -f ./test/test_lac.py
          rm -f ./test/test_dict.py
          rm -f ./test/test_list.py
          rm -f ./test/test_sentiment.py

      - name: Run unit tests
        working-directory: ./tests/
        run: |
          bash ./run_all_paddle_ci.sh
