name: Paddle Nightly build

env:
  TZ: Asia/Shanghai
  GITHUB_WORKSPACE: /home/runner/work/

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request: # TODO: clean
  workflow_dispatch:

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version-with-wheel:
          # - ["3.8", "paddlepaddle-0.0.0-cp38-cp38-linux_x86_64.whl"]
          # - ["3.9", "paddlepaddle-0.0.0-cp39-cp39-linux_x86_64.whl"]
          - ["3.10", "paddlepaddle-0.0.0-cp310-cp310-linux_x86_64.whl"]
        include:
          - os: ubuntu-latest
            python-version-with-wheel: ["3.10", "paddlepaddle-0.0.0-cp310-cp310-linux_x86_64.whl"]
            install-python: true
    runs-on: ${{ matrix.os }}
    container:
      image: paddlepaddle/paddle:latest-dev
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
    name: paddle-py${{ matrix.python-version-with-wheel[0] }}-nightly
    steps:
      - name: git clone
        run: |
          git clone https://github.com/2742195759/Paddle
          cd Paddle
          git submodule init
          git submodule update

      - name: init system
        run: |
          apt-get update
          apt-get install wget curl git make cmake bzip2 neofetch -y

      - name: install Python
        if: ${{matrix.install-python}}
        run: |
          ln -s /usr/lib/python3/dist-packages/apt_pkg.cpython-36m-x86_64-linux-gnu.so /usr/lib/python3/dist-packages/apt_pkg.so
          python3 -m pip install pgi
          apt-get install -y software-properties-common
          add-apt-repository ppa:deadsnakes/ppa
          apt-get install -y python3.10 python3.10-dev python3.10-venv python3.10-distutils

      - name: install pip packages
        run: |
          python${{matrix.python-version-with-wheel[0]}} -m pip install --upgrade pip
          python${{matrix.python-version-with-wheel[0]}} -m pip install wheel pyyaml
          cd Paddle
          python${{matrix.python-version-with-wheel[0]}} -m pip install -r python/requirements.txt

      - name: get env
        run: |
          cd Paddle
          python${{matrix.python-version-with-wheel[0]}} -m pip install distro
          python${{matrix.python-version-with-wheel[0]}} tools/summary_env.py
          neofetch

      - name: paddle build
        run: |
          cd Paddle
          mkdir build
          cd build
          cmake .. -DPY_VERSION=${{matrix.python-version-with-wheel[0]}} -DWITH_GPU=OFF
          make -j$(nproc)

      - name: paddle install
        run: |
          cd Paddle/build
          python${{matrix.python-version-with-wheel[0]}} -m pip install python/dist/${{matrix.python-version-with-wheel[1]}}

      - name: paddle run check
        run: |
          python${{matrix.python-version-with-wheel[0]}} -c "import paddle;paddle.utils.run_check()"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python-version-with-wheel[1] }}
          path: Paddle/build/python/dist/${{ matrix.python-version-with-wheel[1] }}
          retention-days: 90
