name: PaddleDy2staicTests

on:
  push:
    branches: [develop]
  pull_request:
  workflow_dispatch:

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version-with-wheel:
          - ["3.8", "paddlepaddle-0.0.0-cp38-cp38-linux_x86_64.whl"]
          - ["3.9", "paddlepaddle-0.0.0-cp39-cp39-linux_x86_64.whl"]
          - ["3.10", "paddlepaddle-0.0.0-cp310-cp310-linux_x86_64.whl"]
    runs-on: ${{ matrix.os }}
    name: python ${{ matrix.python-version-with-wheel[0] }} dy2st unittests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version-with-wheel[0] }}

      # TODO(gouzil): temporary solution
      - name: Download paddle wheel
        run: |
          wget --no-verbose https://github.com/gouzil/paddle_Nightly_build/releases/download/master/${{ matrix.python-version-with-wheel[1] }}

      - name: Install dependencies
        run: |
          pip install ${{ matrix.python-version-with-wheel[1] }}
          pip install ".[paddle-test]"

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/paddle
          key: ${{ runner.os }}-${{ matrix.python-version-with-wheel[0] }}-paddle-cache-v1

      - name: Clone paddle tests
        working-directory: ./tests/
        run: |
          git clone https://github.com/PaddlePaddle/Paddle
          cd Paddle
          git remote add upstream https://github.com/PaddlePaddle/Paddle
          git fetch upstream pull/54202/head:symbolic_translate
          git checkout symbolic_translate

      - name: Run unit tests
        working-directory: ./tests/
        run: |
          bash ./run_all_paddle_ci.sh
