name: Test

on:
  push:
    branches: [execution]
  pull_request:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    name: Run unit tests and examples
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          # Currently, we only support Python 3.8
          python-version: '3.8'

      - name: Install dependencies
        run: |
          wget https://paddle-ci.gz.bcebos.com/dy2st/fallback/linux-whl/paddlepaddle_gpu-0.0.0-cp38-cp38-linux_x86_64.whl
          pip install paddlepaddle_gpu-0.0.0-cp38-cp38-linux_x86_64.whl
          pip install -r requirements.txt

      - name: Run unit tests
        working-directory: ./tests/test_executor/
        run: |
          bash run_all.sh
