name: Test

on:
  push:
    branches: [execution]
  pull_request:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ${{ matrix.python-version }}
    name: ${{ matrix.os }} - python ${{ matrix.python-version }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8','3.9']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          # Currently, we only support Python 3.8
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          wget https://paddle-ci.gz.bcebos.com/dy2st/fallback/linux-whl/paddlepaddle_gpu-0.0.0-cp38-cp38-linux_x86_64.whl
          pip install paddlepaddle_gpu-0.0.0-cp38-cp38-linux_x86_64.whl
          pip install -r requirements.txt

      - name: Run unit tests
        working-directory: ./tests/
        run: |
          bash run_all.sh
