name: UnitTest

on:
  push:
    branches: [develop]
  pull_request:
  workflow_dispatch:

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}
    name: python ${{ matrix.python-version }} unittests
    container:
      image: paddlepaddle/paddle:latest-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python${{ matrix.python-version }} -m pip install paddlepaddle==0.0.0 -f https://www.paddlepaddle.org.cn/whl/linux/cpu-mkl/develop.html
          python${{ matrix.python-version }} -m pip install -e ".[dev]"
      - name: Run unit tests
        working-directory: ./tests/
        run: |
          alias python='/usr/bin/python${{ matrix.python-version }}'
          bash run_all.sh
      - name: Run examples
        working-directory: ./examples/
        run: |
          alias python='/usr/bin/python${{ matrix.python-version }}'
          bash run_all.sh
      - name: Run xdoctest
        working-directory: ./
        run: |
          xdoctest sot
